### ISSUE TITLE
Support "url" connection string in settings

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-kv-redis#15]
Most LoopBack connectors allow users to provide a single setting called "url" that overrides any other settings like "host" and "port". This is used to override datasource configuration via environmental variables, for example.

**Comment by superkhau** [comment]
A bit of confusion, is this different than what you have at https://github.com/strongloop/loopback-connector-kv-redis/blob/master/lib/kv-redis.js#L59? Or is it just to make sure we can take in a `url` property in `datasources.json`?

**Comment by superkhau** [comment]
Added URL property to PR at https://github.com/strongloop/loopback-connector-kv-redis/issues/15#issue-182727742

**Comment by bajtos** [comment]
> A bit of confusion, is this different than what you have at https://github.com/strongloop/loopback-connector-kv-redis/blob/master/lib/kv-redis.js#L59? Or is it just to make sure we can take in a url property in datasources.json?

You mean https://github.com/strongloop/loopback-connector-kv-redis/blob/c2b202c491736f2c47167ee794634c429505618d/lib/kv-redis.js#L61?

I did not realise the code is already there, good catch! Could you please check that we have unit tests checking the desired behaviour (url overrides all other settings)?

> Added url property to PR at strongloop/loopback-workspace#332

That's the second part of this story 👍

**Comment by superkhau** [comment]
>I did not realise the code is already there, good catch! Could you please check that we have unit tests checking the desired behaviour (url overrides all other settings)?

PR to verfiy @ #23

**Comment by superkhau** [comment]
Landed #23, closing.
