### ISSUE TITLE
Add delete operation

### ISSUE THREAD

**Issue by gclyne** [strongloop/loopback-connector-kv-redis#28]
Already implemented in kv-memory connectors. The redis connector implementation is simple,
basically copy the get method, and replace 'get' with 'del'. 

https://redis.io/commands/del

**Comment by ritch** [comment]
Glad to hear this is being used. Moving this to a higher priority since it is a lot of value compared to the code/time. 👍

**Comment by superkhau** [comment]
@gclyne Thanks for creating the issue. Feel free to bug @ritch to get it planned. ;)
