### ISSUE TITLE
Crash on npm start

### ISSUE THREAD

**Issue by tokidoki11** [strongloop/loopback-connector-kv-redis#38]
I defined datasource for redis like this
```
 {
    "host": "127.0.0.1",
    "port": 6379,
    "name": "xrjti-token-redis",
    "connector": "kv-redis"
  }
```
when I tried to run `npm start`, it crashed
```
/xr-jti-api/node_modules/loopback-datasource-juggler/lib/datasource.js:542
          modelClass[relation.type].call(modelClass, relationName, params);
```

<img width="942" alt="image" src="https://user-images.githubusercontent.com/7564844/40103325-42ac9cce-5917-11e8-886b-37ae10dd068b.png">

**Comment by bajtos** [comment]
@tokidoki11 Please note this connector should be used with models inheriting from `KeyValueModel`, not from `PersistedModel`. Relations are not supported for key-value models.
