### ISSUE TITLE
WATCH

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-connector-kv-redis#4]
Add the ability to watch keys for changes. I think its ok if we add this support for only this connector, unless there is enough overlap in other data sources.

@bajtos

**Comment by bajtos** [comment]
Let's do this in KVAO. We are already adding `ttl` method there, which is not available in `memcached` connector for example ([link](http://stackoverflow.com/questions/5329431/memcache-get-key-expiry-times)).
