### ISSUE TITLE
expire() method not working

### ISSUE THREAD

**Issue by guptadeepanshu3** [strongloop/loopback-connector-kv-redis#48]
# Description/Steps to reproduce
The key expiration time is not set by the expire method.

1. Create new redis key with set(key,data) method.
2. Try to set expiry time for the key by using expire(key,ttl).

Error: key not generated or unable to set expiry time.
# Additional information
Sometimes if I use expire method after set method, even key is also getting generated.

**Comment by bajtos** [comment]
@guptadeepanshu3 thank you for reporting the problem. Please post a code sample we can run to reproduce the problem. A small application would be even better - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report. Ideally, write an automated test we can run via `npm test`, one that fails with the current LoopBack version.
