### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by vikramkh** [strongloop/loopback-connector-kv-redis#51]
## Steps to reproduce

I have a redis server that has 'requirepass' enabled. I set a password when creating the redis kv repository using the lb4 datasource command, however I get the error:

[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.

My redis.datasource.config.json file looks like this:

{
  "name": "redis",
  "connector": "kv-redis",
  "url": "<myHost",
  "host": "<myHost>",
  "port": 6379,
  "password": "<myPassword>",
  "db": 0
}

darwin x64 10.15.3
├── @loopback/authentication@3.3.3
├── @loopback/authentication-passport@1.1.3
├── @loopback/boot@1.7.4
├── @loopback/context@2.1.1
├── @loopback/core@1.12.4
├── @loopback/openapi-v3@2.0.0
├── @loopback/repository@1.19.1
├── @loopback/rest@2.0.0
├── @loopback/rest-explorer@1.4.10
├── @loopback/service-proxy@1.3.17
├── loopback-connector-kv-redis@3.0.2

**Comment by vikramkh** [comment]
Ah it seems it uses the URL rather than the other parameters. It seems to be working now that I have passed in a proper URL

**Comment by krsubbar** [comment]
@vikramkh I am still facing this issue after specifying the URL. The URL format I tried is redis://:$password@$host:$port/$db.

Can you check if this URL for matches is same as the one working for you?
