### ISSUE TITLE
Lock Support

### ISSUE THREAD

**Issue by rajanmishra** [strongloop/loopback-connector-kv-redis#55]
Support of lock to stop concurrency with finance domain application.

**Comment by bajtos** [comment]
Thank you for raising this feature request. Would you like to contribute the implementation yourself? Also what version of LoopBack are you using - LB3 or LB4?

**Comment by rajanmishra** [comment]
I am using LB4, Yes I can start with the implementation to support the same.

**Comment by bajtos** [comment]
> I am using LB4

👍 

> Yes I can start with the implementation to support the same with some mentorship.

That's great to hear! I am not familiar with Redis locks myself, so I'll need some mentorship from you too 😄 

Can you please point me to Redis documentation explaining locking? Is it a new command (like `DEL`) or an option to be used with other commands (e.g. `ttl`?)

**Comment by rajanmishra** [comment]
Hi, Hopes you are doing great.
It's not related to the command available in Redis, it's more of a use case using Redis.
So someone's can create distributed locks using the Redis to make it concurrency safe, valid for the KV connector's getting, and setting functions.
I was looking for something so that we can easily use the npm module.
https://github.com/mike-marcacci/node-redlock.

Currently, I've used this one with my current project - https://www.npmjs.com/package/async-lock worked perfectly fine, but it's not distributed.
 
Please let me know your thought regarding integrating node-redlock or alike with KV connector to give others an option to use locking out of the box.

**Comment by bajtos** [comment]
Thank you for the pointers.

The goal of loopback-connector-redis is to provide Redis-based implementation of LoopBack's KeyValue data access APIs. How do you envision to fit the locking functionality into that design? Will this be a features specific to Redis only or is it something that could be potentially implemented by other KeyValue connectors too?

I think it would be best to start with describing use cases. Let's say the connector implements locking. How would you use that feature in a LoopBack application? Can you please post a code snippet showing the intended use?
